name: trivia_night
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  firebase_auth: ^4.2.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cloud_firestore: ^4.4.0
  http: ^0.13.5
  html: ^0.15.0
  html_unescape: ^2.0.0
  font_awesome_flutter: ^10.5.0
  flutter_custom_clippers: ^2.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
