// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhLdNC3RkIctZc7VGYQh62NkfRfe9YGvg',
    appId: '1:533464560946:web:ff524e31cb9ee899e1932b',
    messagingSenderId: '533464560946',
    projectId: 'trivia-night-app',
    authDomain: 'trivia-night-app.firebaseapp.com',
    storageBucket: 'trivia-night-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwn5GeNcZBlMPguqLnzteD1OqxgopVuck',
    appId: '1:533464560946:android:e3d898f8d66435fae1932b',
    messagingSenderId: '533464560946',
    projectId: 'trivia-night-app',
    storageBucket: 'trivia-night-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbh6oEIUme_l8Qyj2BgK7ZPwwwtNRBjUo',
    appId: '1:533464560946:ios:533fb28c44bc5f21e1932b',
    messagingSenderId: '533464560946',
    projectId: 'trivia-night-app',
    storageBucket: 'trivia-night-app.appspot.com',
    iosBundleId: 'com.example.triviaNight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbh6oEIUme_l8Qyj2BgK7ZPwwwtNRBjUo',
    appId: '1:533464560946:ios:db8738fc64dd348fe1932b',
    messagingSenderId: '533464560946',
    projectId: 'trivia-night-app',
    storageBucket: 'trivia-night-app.appspot.com',
    iosBundleId: 'com.example.triviaNight.RunnerTests',
  );
}
